name: Unit-test

on:
  push:
    branches: [ master ]

jobs:

  python-test:
    name: Python-unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Test
      run: |
        pip install pytest
        pytest

  golang-test:
    name: Golang-unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Test
      run: go test -cover ./...
