name: Unit-test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:

  python-test:
    name: Python-unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Test
      run: |
        pip install pytest
        pytest

  golang-test:
    name: Golang-unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Test
      run: GO111MODULE=auto go test -cover ./...
